version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - BASE_TOKEN=${BASE_TOKEN}
      - OPENING_ID=${OPENING_ID:-9346}
      - STAGE_ID=${STAGE_ID:-75440}
      - NUM_PER_PAGE=${NUM_PER_PAGE:-50}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
